version: '3'
services:
<<<<<<< HEAD
  myapp:
    build: .
    ports:
      - "8080:8080"
=======
        web:
                image: flask_port_v1
                environment:
                        - CRYPTO_KEY=${CRYPTO_KEY}
                build: .
                ports:
                        - "8686:8686"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
>>>>>>> refs/remotes/origin/main
